version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/joshdk/licensor
    steps:
      - checkout
      - run: go get -u github.com/spdx/license-list-data || true
      - run: ./godelw version
      - run: ./godelw verify --apply=false
